spin_manifest_version = 2

[application]
name = "hello"
version = "0.1.0"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]

[[trigger.http]]
route = "/..."
component = "hello"

[component.hello]
source = "build/App.wasm"
files = [{ source = "static/", destination = "/" }]
[component.hello.build]
command = "dotnet publish -o build App.csproj"
